In [4]:
import pandas as pd

In [12]:
location = "airport-codes.csv"
airport_data = pd.read_csv(location)
print(airport_data.shape)
airport_data.head()

(52578, 12)

,ident,type,name,coordinates,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code
0,00A,heliport,Total Rf Heliport,"-74.93360137939453, 40.07080078125",11.0,NaN,US,US-PA,Bensalem,00A,NaN,00A
1,00AA,small_airport,Aero B Ranch Airport,"-101.473911, 38.704022",3435.0,NaN,US,US-KS,Leoti,00AA,NaN,00AA
2,00AK,small_airport,Lowell Field,"-151.695999146, 59.94919968",450.0,NaN,US,US-AK,Anchor Point,00AK,NaN,00AK
3,00AL,small_airport,Epps Airpark,"-86.77030181884766, 34.86479949951172",820.0,NaN,US,US-AL,Harvest,00AL,NaN,00AL
4,00AR,closed,Newport Hospital & Clinic Heliport,"-91.254898, 35.6087",237.0,NaN,US,US-AR,Newport,NaN,NaN,NaN

In [15]:
us_airport_data = airport_data.loc[airport_data["iso_country"] == "US"]
print(us_airport_data.shape)
us_airport_data.head()

(22333, 12)

,ident,type,name,coordinates,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code
0,00A,heliport,Total Rf Heliport,"-74.93360137939453, 40.07080078125",11.0,NaN,US,US-PA,Bensalem,00A,NaN,00A
1,00AA,small_airport,Aero B Ranch Airport,"-101.473911, 38.704022",3435.0,NaN,US,US-KS,Leoti,00AA,NaN,00AA
2,00AK,small_airport,Lowell Field,"-151.695999146, 59.94919968",450.0,NaN,US,US-AK,Anchor Point,00AK,NaN,00AK
3,00AL,small_airport,Epps Airpark,"-86.77030181884766, 34.86479949951172",820.0,NaN,US,US-AL,Harvest,00AL,NaN,00AL
4,00AR,closed,Newport Hospital & Clinic Heliport,"-91.254898, 35.6087",237.0,NaN,US,US-AR,Newport,NaN,NaN,NaN

In [16]:
airport_trim = us_airport_data.loc[us_airport_data["iata_code"].notnull()]
airport_trim.head()

,ident,type,name,coordinates,elevation_ft,continent,iso_country,iso_region,municipality,gps_code,iata_code,local_code
435,07FA,small_airport,Ocean Reef Club Airport,"-80.274803161621, 25.325399398804",8.0,NaN,US,US-FL,Key Largo,07FA,OCA,07FA
587,0AK,small_airport,Pilot Station Airport,"-162.899994, 61.934601",305.0,NaN,US,US-AK,Pilot Station,NaN,PQS,0AK
666,0CO2,small_airport,Buckhorn Ranch Airport,"-106.93282, 38.8518981934",8980.0,NaN,US,US-CO,Crested Butte,0CO2,CSE,0CO2
1080,0TE7,small_airport,LBJ Ranch Airport,"-98.62249755859999, 30.251800537100003",1515.0,NaN,US,US-TX,Johnson City,0TE7,JCY,0TE7
1388,13MA,small_airport,Metropolitan Airport,"-72.31140136719999, 42.223300933800004",418.0,NaN,US,US-MA,Palmer,13MA,PMX,13MA

In [18]:
airport_trim = airport_trim[["iata_code", "name", "coordinates", "iso_region"]]
airport_trim.head()

,iata_code,name,coordinates,iso_region
435,OCA,Ocean Reef Club Airport,"-80.274803161621, 25.325399398804",US-FL
587,PQS,Pilot Station Airport,"-162.899994, 61.934601",US-AK
666,CSE,Buckhorn Ranch Airport,"-106.93282, 38.8518981934",US-CO
1080,JCY,LBJ Ranch Airport,"-98.62249755859999, 30.251800537100003",US-TX
1388,PMX,Metropolitan Airport,"-72.31140136719999, 42.223300933800004",US-MA

In [19]:
airport_trim.to_csv("cleaned_airport_list.csv")